### PR TITLE
Apachify the solr-operator helm chart

### PR DESCRIPTION
**Pull request by HoustonPutman**
A part of: #183 

The helm chart needs some updates now that the solr operator is a part of Apache.

- The maintainers now start with the Solr Dev Community
- Headers have been added to all possible files in the chart
- A NOTICE file has been added for the chart as well.

### CODE REVIEW

**Review by anshumg — APPROVED** [review]
👍🏽

**Comment by vladiceanu** [comment]
Not sure if it's the right place to mention, but https://artifacthub.io/packages/helm/solr-operator/solr-operator also needs to be updated to point to the new chart location

**Comment by HoustonPutman** [comment]
I'll work on that as well @vladiceanu , but it is a separate issue. Thanks for bringing it up!

**Comment by HoustonPutman** [comment]
@vladiceanu , there is a new entry in artifactHub for the Solr Operator (which is verified and official) https://artifacthub.io/packages/helm/apache-solr/solr-operator. It'll be hard to update the README documentation for previous helm chart releases, but at least the install button has the correct information.

**Pull request merged**
